var skills = ["Attack","Defence","Strength","Constitution","Ranged","Prayer","Magic","Cooking","Woodcutting","Fletching","Fishing","Firemaking","Crafting","Smithing","Mining","Herblore","Agility","Thieving","Slayer","Farming","Runecrafting","Hunter","Construction","Summoning","Dungeoneering","Divination","Invention"
]; //Used to turn skill ID's into usable names.

var apiQuestNamesCorrections = []; //Used to correct the API to the wiki names.
apiQuestNamesCorrections["A Rum Deal"] = "Rum Deal";
apiQuestNamesCorrections["As A First Resort..."] = "As a First Resort";
apiQuestNamesCorrections["Chosen Commander"] = "The Chosen Commander";
apiQuestNamesCorrections["Curse of Arrav"] = "The Curse of Arrav";
apiQuestNamesCorrections["Dig Site"] = "The Dig Site";
apiQuestNamesCorrections["Fairy Tale III - Battle at Orks Rift"] = "Fairy Tale III - Battle at Ork's Rift";
apiQuestNamesCorrections["Forgettable Tale of a Drunken Dwarf"] = "Forgettable Tale...";
apiQuestNamesCorrections["Fremennik Isles"] = "The Fremennik Isles";
apiQuestNamesCorrections["Garden of Tranquility"] = "Garden of Tranquillity";
apiQuestNamesCorrections["Great Brain Robbery"] = "The Great Brain Robbery";
apiQuestNamesCorrections["Prisoner of Glouphrie"] = "The Prisoner of Glouphrie";
apiQuestNamesCorrections["Rat Catchers"] = "Ratcatchers";
apiQuestNamesCorrections["Recipe for Disaster"] = "Recipe for Disaster: Defeating the Culinaromancer";
apiQuestNamesCorrections["Recipe for Disaster: Awowogei"] = "Recipe for Disaster: Freeing King Awowogei";
apiQuestNamesCorrections["Recipe for Disaster: Dwarf"] = "Recipe for Disaster: Freeing the Mountain dwarf";
apiQuestNamesCorrections["Recipe for Disaster: Evil Dave"] = "Recipe for Disaster: Freeing Evil Dave";
apiQuestNamesCorrections["Recipe for Disaster: Goblin Generals"] = "Recipe for Disaster: Freeing the Goblin generals";
apiQuestNamesCorrections["Recipe for Disaster: Lumbridge Sage"] = "Recipe for Disaster: Freeing the Lumbridge Sage";
apiQuestNamesCorrections["Recipe for Disaster: Pirate Pete"] = "Recipe for Disaster: Freeing Pirate Pete";
apiQuestNamesCorrections["Recipe for Disaster: Sir Amik Varze"] = "Recipe for Disaster: Freeing Sir Amik Varze";
apiQuestNamesCorrections["Recipe for Disaster: Skrach"] = "Recipe for Disaster: Freeing Skrach Uglogwee";
apiQuestNamesCorrections["Recipe for Disaster: Starting Out"] = "Recipe for Disaster: Another Cook's Quest";
apiQuestNamesCorrections["Slug Menace"] = "The Slug Menace";
apiQuestNamesCorrections["Tale of the Muspah"] = "The Tale of the Muspah";
apiQuestNamesCorrections["Tears of Guthix"] = "Tears of Guthix (quest)";
apiQuestNamesCorrections["The Darkness of Hallowvale"] = "Darkness of Hallowvale";
apiQuestNamesCorrections["The Elemental Workshop I"] = "Elemental Workshop I";
apiQuestNamesCorrections["The Elemental Workshop II"] = "Elemental Workshop II";
apiQuestNamesCorrections["The Elemental Workshop III"] = "Elemental Workshop III";
apiQuestNamesCorrections["The Elemental Workshop IV"] = "Elemental Workshop IV";
apiQuestNamesCorrections["The Watchtower"] = "Watchtower";